# Generated by Django 6.0.2 on 2026-02-13 08:35

from django.db import migrations, models


def copy_phone_to_user(apps, schema_editor):
    """TeacherProfile.phone -> User.phone"""
    User = apps.get_model("accounts", "User")
    TeacherProfile = apps.get_model("accounts", "TeacherProfile")
    for profile in TeacherProfile.objects.select_related("user").all():
        if profile.phone:
            profile.user.phone = profile.phone
            profile.user.save(update_fields=["phone"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_teacherprofile_branch_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(copy_phone_to_user, noop),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='phone',
        ),
    ]
