# Generated by Django 6.0.2 on 2026-02-13 08:38

from django.db import migrations


def copy_full_name_to_user(apps, schema_editor):
    """StudentProfile.full_name -> User.first_name, User.last_name"""
    User = apps.get_model("accounts", "User")
    StudentProfile = apps.get_model("accounts", "StudentProfile")
    for profile in StudentProfile.objects.select_related("user").all():
        if profile.full_name:
            parts = profile.full_name.strip().split(None, 1)
            profile.user.first_name = parts[0] if parts else ""
            profile.user.last_name = parts[1] if len(parts) > 1 else ""
            profile.user.save(update_fields=["first_name", "last_name"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_move_phone_to_user'),
    ]

    operations = [
        migrations.RunPython(copy_full_name_to_user, noop),
        migrations.RemoveField(
            model_name='studentprofile',
            name='full_name',
        ),
    ]
