# Generated by Django 6.0.2 on 2026-02-13 08:43

from django.db import migrations


def backfill_profile_completed(apps, schema_editor):
    """first_name & last_name dolu olan kullanıcılara profile_completed=True"""
    User = apps.get_model("accounts", "User")
    User.objects.filter(
        first_name__isnull=False,
        last_name__isnull=False,
    ).exclude(first_name="").exclude(last_name="").update(profile_completed=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_profile_completed'),
    ]

    operations = [
        migrations.RunPython(backfill_profile_completed, noop),
    ]
