# Generated by Django 6.0.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_add_user_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthEventLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("event_type", models.CharField(choices=[("LOGIN_SUCCESS", "Login Success"), ("LOGIN_FAIL", "Login Fail"), ("LOGOUT", "Logout"), ("REFRESH", "Token Refresh")], max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="auth_event_logs", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="autheventlog",
            index=models.Index(fields=["created_at"], name="accounts_au_created_8f0e0e_idx"),
        ),
        migrations.AddIndex(
            model_name="autheventlog",
            index=models.Index(fields=["user", "created_at"], name="accounts_au_user_id_7a8f3d_idx"),
        ),
        migrations.AddIndex(
            model_name="autheventlog",
            index=models.Index(fields=["event_type", "created_at"], name="accounts_au_event_t_9c2e1a_idx"),
        ),
    ]
