# Generated by Django 6.0.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_add_avatar_to_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token_version",
            field=models.IntegerField(default=0),
        ),
    ]
