# Generated by Django 6.0.2 on 2026-02-13 21:26

import django.db.models.deletion
from django.db import migrations, models


def seed_grade_levels(apps, schema_editor):
    """Türkiye yaygın sınıf düzeyleri ve sınav türleri - idempotent."""
    GradeLevel = apps.get_model("catalog", "GradeLevel")

    SEED_DATA = [
        # CLASS: Okul öncesi, 1-12, Hazırlık
        ("okul-oncesi", "Okul Öncesi", "CLASS"),
        ("sinif-1", "1. Sınıf", "CLASS"),
        ("sinif-2", "2. Sınıf", "CLASS"),
        ("sinif-3", "3. Sınıf", "CLASS"),
        ("sinif-4", "4. Sınıf", "CLASS"),
        ("sinif-5", "5. Sınıf", "CLASS"),
        ("sinif-6", "6. Sınıf", "CLASS"),
        ("sinif-7", "7. Sınıf", "CLASS"),
        ("sinif-8", "8. Sınıf", "CLASS"),
        ("sinif-9", "9. Sınıf", "CLASS"),
        ("sinif-10", "10. Sınıf", "CLASS"),
        ("sinif-11", "11. Sınıf", "CLASS"),
        ("sinif-12", "12. Sınıf", "CLASS"),
        ("hazirlik", "Hazırlık", "CLASS"),
        # EXAM
        ("lgs", "LGS", "EXAM"),
        ("yks", "YKS", "EXAM"),
        ("tyt", "TYT", "EXAM"),
        ("ayt", "AYT", "EXAM"),
        ("kpss", "KPSS", "EXAM"),
        ("kpss-lisans", "KPSS Lisans", "EXAM"),
        ("kpss-onlisans", "KPSS Önlisans", "EXAM"),
        ("kpss-ortaogretim", "KPSS Ortaöğretim", "EXAM"),
        ("ales", "ALES", "EXAM"),
        ("dgs", "DGS", "EXAM"),
        ("yds", "YDS", "EXAM"),
        ("yokdil", "YÖKDİL", "EXAM"),
        ("tus", "TUS", "EXAM"),
        ("dus", "DUS", "EXAM"),
        ("msu", "MSÜ", "EXAM"),
        ("ags", "AGS", "EXAM"),
        ("oabt", "ÖABT", "EXAM"),
    ]

    for order, (code, name, kind) in enumerate(SEED_DATA, start=1):
        GradeLevel.objects.update_or_create(
            code=code,
            defaults={"name": name, "kind": kind, "is_active": True, "order": order},
        )


def assign_grade_level_to_lesson_categories(apps, schema_editor):
    """Mevcut LessonCategory kayıtlarına varsayılan grade_level ata."""
    GradeLevel = apps.get_model("catalog", "GradeLevel")
    LessonCategory = apps.get_model("catalog", "LessonCategory")

    default_gl = GradeLevel.objects.filter(code="sinif-1").first()
    if not default_gl:
        default_gl = GradeLevel.objects.order_by("order").first()
    if default_gl:
        LessonCategory.objects.filter(grade_level__isnull=True).update(grade_level=default_gl)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_catalog_updates_order_topic_lesson_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.SlugField(blank=True, unique=True)),
                ('kind', models.CharField(choices=[('CLASS', 'Sınıf'), ('EXAM', 'Sınav'), ('OTHER', 'Diğer')], default='CLASS', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sınıf Düzeyi',
                'verbose_name_plural': 'Sınıf Düzeyleri',
                'ordering': [models.OrderBy(models.F('order'), nulls_last=True), 'name', 'created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='lessoncategory',
            options={'ordering': [models.OrderBy(models.F('order'), nulls_last=True), 'name', 'created_at'], 'verbose_name': 'Ders', 'verbose_name_plural': 'Dersler'},
        ),
        migrations.AlterModelOptions(
            name='lessontopic',
            options={'ordering': ['lesson_category', models.OrderBy(models.F('order'), nulls_last=True), 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': [models.OrderBy(models.F('order'), nulls_last=True), 'created_at']},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['lesson_category', models.OrderBy(models.F('order'), nulls_last=True), 'created_at']},
        ),
        migrations.AlterField(
            model_name='lessoncategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AddField(
            model_name='lessoncategory',
            name='grade_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lesson_categories', to='catalog.gradelevel'),
        ),
        migrations.RunPython(seed_grade_levels),
        migrations.RunPython(assign_grade_level_to_lesson_categories),
        migrations.AlterField(
            model_name='lessoncategory',
            name='grade_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lesson_categories', to='catalog.gradelevel'),
        ),
        migrations.AlterUniqueTogether(
            name='lessoncategory',
            unique_together={('grade_level', 'name')},
        ),
    ]
