# Generated by Django 6.0.2 on 2026-02-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_grade_level_and_seed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lessoncategory',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='lessoncategory',
            constraint=models.UniqueConstraint(fields=('grade_level', 'name'), name='uniq_lesson_per_grade'),
        ),
    ]
