# Generated by Django 6.0.2 on 2026-02-16 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EDUMENTOR', max_length=100)),
                ('tagline', models.CharField(blank=True, default='', max_length=200)),
                ('support_email', models.EmailField(blank=True, default='', max_length=254)),
                ('support_phone', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(default='Europe/Istanbul', max_length=50)),
                ('locale', models.CharField(default='tr-TR', max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='branding/')),
                ('maintenance_enabled', models.BooleanField(default=False)),
                ('maintenance_message', models.TextField(blank=True, default='Sistem bakımda. Lütfen daha sonra tekrar deneyin.')),
                ('maintenance_allowed_ips', models.TextField(blank=True, default='')),
                ('smtp_enabled', models.BooleanField(default=False)),
                ('smtp_host', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_username', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_password', models.CharField(blank=True, default='', max_length=255)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('force_strong_passwords', models.BooleanField(default=True)),
                ('force_must_change_password_on_admin_reset', models.BooleanField(default=True)),
                ('session_notice_enabled', models.BooleanField(default=True)),
                ('analytics_tracking_id', models.CharField(blank=True, default='', max_length=255)),
                ('sentry_dsn', models.CharField(blank=True, default='', max_length=500)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site Ayarları',
                'verbose_name_plural': 'Site Ayarları',
            },
        ),
    ]
